---

- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: Create YUM repo file
  yum_repository:
    name: pulp
    description: Pulp Project repository
    baseurl: "{{ pulp_yumrepo_url }}"
    gpgkey: "{{ pulp_yumrepo_gpgkey }}"
    params: "{{ pulp_yumrepo_params }}"
  tags:
    - pulp_pkg

- include: pulp_server.yaml
  when: pulp_install_server == true

- include: pulp_admin.yaml
  when: pulp_install_admin == true

- include: pulp_consumer.yaml
  when: pulp_install_consumer == true
