---

- name: Restart Web service
  service:
    name: "{{ pulp_web_service }}"
    state: restarted

- name: Restart Pulp Workers service
  service:
    name: pulp_workers
    state: restarted

- name: Restart Pulp Celerybeat service
  service:
    name: pulp_celerybeat
    state: restarted
  when: pulp_run_celerybeat

- name: Restart Pulp Resource Manager service
  service:
    name: pulp_resource_manager
    state: restarted
  when: pulp_run_resource_manager

- name: Restart goferd service
  service:
    name: goferd
    state: restarted
